### ISSUE TITLE
无网络/网络比较差的时候，只显示“似乎已断开与互联网的连接”

### ISSUE THREAD

**Issue by konkong** [im3x/Scriptables#18]
反馈前，先赞一波！老哥好评！

这个反馈如果优化下就更好了
就是在无网络或者网络比较差时，多次熄屏亮屏后，就只是个感叹号了

**Comment by im3x-dev** [comment]
是的，因为插件一般会5分钟左右刷新一次（请求网络）
目前我们已经有部分组件进行了离线优化（缓存+判断请求错误）
更好的用户体验需要程序一步步完善
