### ISSUE TITLE
组件调试

### ISSUE THREAD

**Issue by GzhiYi** [im3x/Scriptables#22]
Hello。
请问这是目前组件的调试方案吗？

> 2020/10/13 17:00更新：加载器支持输入第三方开发者的插件配置
> 比如开发者 user-a， fork 了本项目到自己的仓库，编辑了 welcome/latest.js 组件脚本，那么用户在添加桌面组件时，输入参数：user-a/welcome@latest 即可加载第三方开发者仓库的组件代码。
> 注意：由于用户可能使用的是Gitee源加载器，所以你应该也需要前往 Gitee，创建同名用户+仓库，同步 github 仓库项目
（和之前的参数区别就是前边多了 用户名/ 格式）
> 开发者可以直接复制 template.sample.js 代码，打开 Scriptable 应用，添加粘贴代码，然后根据底部的注释取消注释相关代码，即可进行测试、独立运行操作。
待测试完毕，可直接上传到自己的仓库项目中，然后根据上边方法进行远程加载测试。

这样感觉会比较麻烦。

**Comment by GzhiYi** [comment]
#23 
本地起个服务对于调试脚本帮助还可以，看是否会有助于提升开发的效率。

**Comment by im3x-dev** [comment]
本地调试开发，是直接新建一个组件（template.sample.js），注释底部 .test、.init 代码，即可测试、运行

测试运行完毕再上传远程
