### ISSUE TITLE
锦囊妙计文本

### ISSUE THREAD

**Issue by Aaloone** [im3x/Scriptables#27]
锦囊妙计不知对能不能改进点击可以复制文本。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by im3x-dev** [comment]
这个很棒的插件作者是 @delfws

**Comment by delfws** [comment]
> 锦囊妙计不知对能不能改进点击可以复制文本。
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

目前做的是点击进入Scriptable软件内弹出复制文本，然后是需要做成点击自动复制的效果对吧

**Comment by im3x-dev** [comment]
#28

**Comment by Aaloone** [comment]
都是大佬，感谢感谢
