### ISSUE TITLE
运行loader.gitee.js的时候提示语法错误

### ISSUE THREAD

**Issue by ghost** [im3x/Scriptables#3]
![image](https://user-images.githubusercontent.com/26181512/95706030-4ce39180-0c88-11eb-8a12-9595c5d6bd30.png)

**Comment by im3x-dev** [comment]
你好，请问代码是经过修改了吗？我这边多次复制测试+直接安装脚本测试没能遇到你截图的错误

方便的话截代码相关的图 谢谢～（看错误提示是29行左右）

Scriptable 的左上角设置->Editor 可以开启行数显示

**Comment by ghost** [comment]
我是直接从https://raw.githubusercontent.com/im3x/Scriptables/main/loader.github.js复制到app种运行的，会遇到这个错误，但是按照readme文档描述从浏览器下载文件再使用app打开就没有问题，应该是我复制除了偏差。打扰作者了，不好意思🤣
