### ISSUE TITLE
彩云天气最近一直出错

### ISSUE THREAD

**Issue by rainbye** [im3x/Scriptables#31]
![832F4A7A-C590-4046-AE1E-F8771E6CDE81](https://user-images.githubusercontent.com/50487283/97770501-de02a580-1b6e-11eb-9e51-7f300fd0ec76.png)

**Comment by Paaaanda** [comment]
大哥，你的图标怎么搞的，需要先跳转捷径吗

**Comment by im3x-dev** [comment]
彩云天气现在接口key已经被滥用失效了。
可以用「小件件」小程序里的（小天气）小组件，支持背景透明设置

**Comment by vaetime** [comment]
> 先跳
第三方app不跳，系统应用稍稍闪一下，用的捷径换的图标😘

**Comment by rainbye** [comment]
> 大哥，你的图标怎么搞的，需要先跳转捷径吗

第三方app不跳，系统应用稍稍闪一下，用的捷径换的图标😘

**Comment by rainbye** [comment]
> 大哥，你的图标怎么搞的，需要先跳转捷径吗

https://www.icloud.com/shortcuts/319fb256aa3f450c83a6cefdebdabe2d
