### ISSUE TITLE
从2020.11.7开始有几个小组件出问题了

### ISSUE THREAD

**Issue by jxmnhm** [im3x/Scriptables#34]
都是通过loader.gitee这个插件安装的：
联通话费查询签到版：error on line 39:27:TypeError:undefined is not an object(evaluating `data.data.dataList`)
微信扫一扫：Object is not a constructor（evaluating`new M(this.opt[`args`],this)`）
支付宝盒子：Object is not a constructor（evaluating`new M(this.opt[`args`],this)`）
微博热榜：Object is not a constructor（evaluating`new M(this.opt[`args`],this)`）
请问应该怎么处理？

**Comment by im3x-dev** [comment]
联通话费查询这个我们项目的仓库并没有此插件。
其他的插件，是不需要安装的，在桌面添加小组件时传递自定义参数即可
