### ISSUE TITLE
搞不懂怎么发布？

### ISSUE THREAD

**Issue by ilaipi** [im3x/Scriptables#35]
readme里写的是pull到本分支，意思提pr到你这边合并之后才能发布吗？

我看小程序里有那么多的  也没合并过来 都发布了，怎么发布呢？谢谢

**Comment by im3x-dev** [comment]
小程序的插件和开源版本的插件不一样（小程序目前不支持提交插件，但是你可以提交插件到本开源仓库提供给其他用户学习使用）
